apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-server
spec:
  replicas: 10              # Set your desired 4 replicas here
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80