apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-resume-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Endeshaw90/DevOps_Resume
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  replicas: 4